apiVersion: apps/v1
kind: Deployment
metadata:
  name: eg-static-site-deployment
  labels:
    app: eg-static-site
spec:
  selector:
    matchLabels:
      app: eg-static-site
  replicas: 1
  template:
    metadata:
      labels:
        app: eg-static-site
    spec:
      containers:
      - name: eg-static-site # ???
        image: "replaced by build"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
      # imagePullSecrets:
      # - name: ghcr-docker
---
apiVersion: v1
kind: Service
metadata:
  name: eg-static-site-service
spec:
  # type: NodePort
  selector:
    app: eg-static-site
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      # nodePort: 30007
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eg-static-site-ingress
spec:
  # tls:
  # - hosts:
  #   - cafe.example.com
  #   secretName: cafe-secret
  ingressClassName: nginx
  rules:
  - host: eg.k8s.zk.io
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: eg-static-site-service
            port:
              number: 80
