#!/usr/bin/env bash


# kubectl delete -f cert-manager-v1.3.1.yml
# kubectl delete -f cert-manager-v1.8.0.yml

kubectl apply -f cert-manager-v1.8.0.yml

# Need to wait for the CRDs to be created before we can start making issuers.
# old kubectl wait -f cert-manager-v1.8.0.yml --for condition="established" --timeout=60s
kubectl wait --for condition=established --timeout=60s crd/clusterissuers.cert-manager.io

kubectl apply -f letsencrypt-staging.yaml

kubectl apply -f letsencrypt-prod.yaml
