#!/usr/bin/env bash

kubectl apply -f cert-manager-v1.8.0.yml

# Need to wait for the CRDs to be created before we can start making issuers.
kubectl wait --for condition="established" crd -f cert-manager-v1.8.0.yml


kubectl apply -f letsencrypt-staging.yaml

kubectl apply -f letsencrypt-prod.yaml
