name: on-push # dsx rename

on:
  workflow_dispatch:
  push:
    # # Publish `$default-branch` as Docker `latest` image.
    # branches:
    #   - $default-branch

    # # Publish `v1.2.3` tags as releases.
    # tags:
    #   - v*

  # Run tests for any PRs.
  pull_request:

env:
  DSXWAT: dsx

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [nginx-ingress, cert-manager]
    steps:
      - uses: actions/checkout@v2

      - name: Build step
        working-directory: ${{ matrix.folder }}
        run: |
          echo ${{ matrix.folder }}: Build
          echo ./build

      - name: Deploy step
        working-directory: ${{ matrix.folder }}
        run: |
          echo ${{ matrix.folder }}: Deploy
          echo ./deploy


  deployments:
    needs: infrastructure
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [eg-static-site, eg-rest-server]
    steps:
      - uses: actions/checkout@v2

      - name: Build step
        working-directory: ${{ matrix.folder }}
        run: |
          echo ${{ matrix.folder }}: Build
          echo ./build

      - name: Deploy step
        working-directory: ${{ matrix.folder }}
        run: |
          echo ${{ matrix.folder }}: Deploy
          echo ./deploy
